[07/Nov/2013 14:34:38] INFO :: csv :: 1 :: admin@ucjeps.cspace.berkeley.edu :: accessionnumber_txt:(+UC956503) :: accession=UC956503&displayType=full&maxresults=1
[07/Nov/2013 14:35:43] INFO :: csv :: 1 :: admin@ucjeps.cspace.berkeley.edu :: accessionnumber_txt:(+UC956503) :: accession=UC956503&displayType=full&maxresults=1
[07/Nov/2013 14:58:42] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 14:58:45] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 105, in eloan
    borcontact = getfromXML(loanoutXML,'.//borrowersContact')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 92, in getfromXML
    result = element.find(xpath)
TypeError: expected a character buffer object
[07/Nov/2013 14:59:53] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 22:33:59] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 22:34:10] WARNING :: Not Found: /favicon.ico
[07/Nov/2013 22:34:10] WARNING :: Not Found: /favicon.ico
[07/Nov/2013 22:35:18] INFO :: start :: 3 :: - ::  (id:(+af6fecfb-6831-4c09-9e36-0f025a1d0295) OR id:(+24ae175b-1dd9-4c7d-8c6a-d817c6100218) OR id:(+5fb80054-415d-4dab-b239-bf0211a2ed2d))  :: csid=af6fecfb-6831-4c09-9e36-0f025a1d0295 OR 24ae175b-1dd9-4c7d-8c6a-d817c6100218 OR 5fb80054-415d-4dab-b239-bf0211a2ed2d&displayType=full&maxresults=2000
[07/Nov/2013 23:20:46] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 23:20:48] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/cspace_django_site/urls.py", line 30, in <module>
    url(r'^public/', include('eloan.urls', namespace='eloan')),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/urls.py", line 4, in <module>
    from eloan import views
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 157
    objNamesForContext =
                        ^
SyntaxError: invalid syntax
[07/Nov/2013 23:25:09] WARNING :: Reinitializing the site.
[07/Nov/2013 23:27:13] INFO :: start :: 1 :: - :: accessionnumber_txt:(+UC956503) :: accession=UC956503&displayType=full&maxresults=1
[07/Nov/2013 23:34:32] INFO :: results.list :: 1 :: - :: accessionnumber_txt:(+UC956503) AND  (determination_s:"Streptanthus barbiger Greene")  :: accession=UC956503&determination=Streptanthus barbiger Greene&displayType=list&maxresults=100
[07/Nov/2013 23:34:41] INFO :: results.list :: 1 :: - :: accessionnumber_txt:(+UC956503) AND  (determination_s:"Streptanthus barbiger Greene")  :: accession=UC956503&determination=Streptanthus barbiger Greene&displayType=list&maxresults=100
[07/Nov/2013 23:34:46] INFO :: results.list :: 1 :: - :: accessionnumber_txt:(+UC956503) AND majorgroup_s:"Spermatophytes" AND  (determination_s:"Streptanthus barbiger Greene")  :: accession=UC956503&majorgroup=Spermatophytes&determination=Streptanthus barbiger Greene&displayType=list&maxresults=100
[07/Nov/2013 23:35:00] INFO :: results.list :: 1 :: - :: accessionnumber_txt:(+UC956503) AND majorgroup_s:"Spermatophytes" AND  (determination_s:"Streptanthus barbiger Greene")  AND  (collector_s:"Freed W. Hoffman")  :: accession=UC956503&majorgroup=Spermatophytes&determination=Streptanthus barbiger Greene&collector=Freed W. Hoffman&displayType=list&maxresults=100
[07/Nov/2013 23:37:37] INFO :: results.list :: 0 :: - ::  (accessionnumber_txt:(+UC956503, +UCJEPS2345))  :: accession=UC956503, UCJEPS2345&displayType=list&maxresults=100
[07/Nov/2013 23:37:41] INFO :: results.list :: 0 :: - ::  (accessionnumber_txt:(+UC956503, +UCJEPS2345))  :: accession=UC956503, UCJEPS2345&displayType=list&maxresults=100
[07/Nov/2013 23:37:55] INFO :: results.list :: 1 :: - ::  (accessionnumber_txt:(+UC956503) OR accessionnumber_txt:(+UCJEPS2345))  :: accession=UC956503 OR UCJEPS2345&displayType=list&maxresults=100
[07/Nov/2013 23:38:15] INFO :: results.list :: 1 :: - :: accessionnumber_txt:(+UC956502) :: accession=UC956502 &displayType=list&maxresults=100
[07/Nov/2013 23:38:33] INFO :: results.list :: 0 :: - ::  (accessionnumber_txt:(+UC956502, +UC956503))  :: accession=UC956502, UC956503 &displayType=list&maxresults=100
[07/Nov/2013 23:38:45] INFO :: results.list :: 2 :: - ::  (accessionnumber_txt:(+UC956502) OR accessionnumber_txt:(+UC956503))  :: accession=UC956502 OR UC956503 &displayType=list&maxresults=100
[07/Nov/2013 23:46:18] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 23:46:22] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 132, in eloan
    objNum = '' if objectNumber is None else objectNumber.text
NameError: global name 'objectNumber' is not defined
[07/Nov/2013 23:47:08] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 23:47:12] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 132, in eloan
    objNum = '' if objNum is None else objNum.text
AttributeError: 'str' object has no attribute 'text'
[07/Nov/2013 23:47:46] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 23:47:50] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objectNumbers.append(objNum)
NameError: global name 'objectNumbers' is not defined
[07/Nov/2013 23:48:26] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 23:49:17] INFO :: start :: 3 :: - ::  (id:(+af6fecfb-6831-4c09-9e36-0f025a1d0295) OR id:(+24ae175b-1dd9-4c7d-8c6a-d817c6100218) OR id:(+5fb80054-415d-4dab-b239-bf0211a2ed2d) OR id:(+UC155270) OR id:(+UC306463) OR id:(+UC647116))  :: csid=af6fecfb-6831-4c09-9e36-0f025a1d0295 OR 24ae175b-1dd9-4c7d-8c6a-d817c6100218 OR 5fb80054-415d-4dab-b239-bf0211a2ed2d OR UC155270 OR UC306463 OR UC647116&displayType=full&maxresults=2000
[07/Nov/2013 23:50:48] INFO :: start :: 3 :: - ::  (id:(+af6fecfb-6831-4c09-9e36-0f025a1d0295) OR id:(+24ae175b-1dd9-4c7d-8c6a-d817c6100218) OR id:(+5fb80054-415d-4dab-b239-bf0211a2ed2d) OR id:(+UC155270) OR id:(+UC306463) OR id:(+UC647116))  :: csid=af6fecfb-6831-4c09-9e36-0f025a1d0295 OR 24ae175b-1dd9-4c7d-8c6a-d817c6100218 OR 5fb80054-415d-4dab-b239-bf0211a2ed2d OR UC155270 OR UC306463 OR UC647116&displayType=full&maxresults=2000
[07/Nov/2013 23:57:34] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[07/Nov/2013 23:57:55] INFO :: start :: 2 :: - ::  (id:(+356a521a-4e91-4646-8975-909d6d4df998) OR id:(+a5996736-9651-4865-8e7d-6cbeae5cf242))  AND  (accessionnumber_txt:(+UC956503) OR accessionnumber_txt:(+UC991142))  :: csid=356a521a-4e91-4646-8975-909d6d4df998 OR a5996736-9651-4865-8e7d-6cbeae5cf242&accession=UC956503 OR UC991142&displayType=full&maxresults=2000
[07/Nov/2013 23:58:12] INFO :: results.full :: 2 :: - ::  (accessionnumber_txt:(+UC956503) OR accessionnumber_txt:(+UC991142))  :: accession=UC956503 OR UC991142&displayType=full&maxresults=2000
[07/Nov/2013 23:58:17] INFO :: results.full :: 2 :: - ::  (accessionnumber_txt:(+UC956503) OR accessionnumber_txt:(+UC991142))  :: accession=UC956503 OR UC991142&displayType=full&maxresults=2000
[07/Nov/2013 23:58:22] INFO :: results.list :: 2 :: - ::  (accessionnumber_txt:(+UC956503) OR accessionnumber_txt:(+UC991142))  :: accession=UC956503 OR UC991142&displayType=list&maxresults=2000
[07/Nov/2013 23:58:25] INFO :: results.grid :: 2 :: - ::  (accessionnumber_txt:(+UC956503) OR accessionnumber_txt:(+UC991142))  :: accession=UC956503 OR UC991142&displayType=grid&maxresults=2000
[08/Nov/2013 19:26:08] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[08/Nov/2013 19:26:08] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/cspace_django_site/urls.py", line 29, in <module>
    url(r'^public/', include('publicsearch.urls', namespace='publicsearch')),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/urls.py", line 4, in <module>
    from publicsearch import views
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/views.py", line 14, in <module>
    from utils import writeCsv, doSearch, setupGoogleMap, setupBMapper, setDisplayType, setConstants, loginfo
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 456, in <module>
    context = doSearch(SOLRSERVER, SOLRCORE, context)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 389, in doSearch
    facet_mincount=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 703, in query
    return self.select(*args, **params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 798, in __call__
    xml = self.raw(**params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 646, in _post
    self._reconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 625, in _reconnect
    self.conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
[08/Nov/2013 19:26:09] WARNING :: Reinitializing the site.
[08/Nov/2013 19:26:09] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[08/Nov/2013 19:26:09] ERROR :: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/cspace_django_site/urls.py", line 29, in <module>
    url(r'^public/', include('publicsearch.urls', namespace='publicsearch')),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/urls.py", line 4, in <module>
    from publicsearch import views
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/views.py", line 14, in <module>
    from utils import writeCsv, doSearch, setupGoogleMap, setupBMapper, setDisplayType, setConstants, loginfo
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 456, in <module>
    context = doSearch(SOLRSERVER, SOLRCORE, context)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 389, in doSearch
    facet_mincount=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 703, in query
    return self.select(*args, **params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 798, in __call__
    xml = self.raw(**params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 646, in _post
    self._reconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 625, in _reconnect
    self.conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
[08/Nov/2013 19:27:21] WARNING :: Reinitializing the site.
[08/Nov/2013 19:27:21] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[08/Nov/2013 19:27:33] WARNING :: Not Found: /favicon.ico
[08/Nov/2013 19:27:42] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[08/Nov/2013 19:28:12] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[08/Nov/2013 19:29:37] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[08/Nov/2013 19:30:09] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 93, in eloan
    raise Exception(errMsg)
Exception: Could not find the loan e23456. Please try another.
[08/Nov/2013 19:30:55] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[08/Nov/2013 19:37:07] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[08/Nov/2013 19:37:13] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[10/Nov/2013 11:53:06] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[10/Nov/2013 11:53:06] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/cspace_django_site/urls.py", line 29, in <module>
    url(r'^public/', include('publicsearch.urls', namespace='publicsearch')),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/urls.py", line 4, in <module>
    from publicsearch import views
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/views.py", line 14, in <module>
    from utils import writeCsv, doSearch, setupGoogleMap, setupBMapper, setDisplayType, setConstants, loginfo
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 456, in <module>
    context = doSearch(SOLRSERVER, SOLRCORE, context)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 389, in doSearch
    facet_mincount=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 703, in query
    return self.select(*args, **params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 798, in __call__
    xml = self.raw(**params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 646, in _post
    self._reconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 625, in _reconnect
    self.conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
[10/Nov/2013 11:53:10] WARNING :: Reinitializing the site.
[10/Nov/2013 11:53:10] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[10/Nov/2013 11:53:10] ERROR :: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/cspace_django_site/urls.py", line 29, in <module>
    url(r'^public/', include('publicsearch.urls', namespace='publicsearch')),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/urls.py", line 4, in <module>
    from publicsearch import views
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/views.py", line 14, in <module>
    from utils import writeCsv, doSearch, setupGoogleMap, setupBMapper, setDisplayType, setConstants, loginfo
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 456, in <module>
    context = doSearch(SOLRSERVER, SOLRCORE, context)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 389, in doSearch
    facet_mincount=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 703, in query
    return self.select(*args, **params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 798, in __call__
    xml = self.raw(**params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 646, in _post
    self._reconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 625, in _reconnect
    self.conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
[10/Nov/2013 11:55:15] WARNING :: Reinitializing the site.
[10/Nov/2013 11:55:15] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[10/Nov/2013 11:56:22] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[10/Nov/2013 11:56:22] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[10/Nov/2013 11:56:24] WARNING :: Not Found: /favicon.ico
[10/Nov/2013 12:05:55] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[10/Nov/2013 12:06:44] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[10/Nov/2013 12:09:03] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[10/Nov/2013 12:30:21] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[10/Nov/2013 12:34:01] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 133, in eloan
    objNum = getfromXML(i,'./object/number')
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 94, in getfromXML
    result = re.sub(r"^.*\)'(.*)'$", "\\1", result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
[10/Nov/2013 12:56:23] INFO :: startup :: - :: http://localhost:8983/solr | ../../imageserver | https://pahma-dev.cspace.berkeley.edu
[10/Nov/2013 12:59:42] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 165, in eloan
    results = doSearch(solr_server, solr_core, solr_context)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 389, in doSearch
    facet_mincount=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 703, in query
    return self.select(*args, **params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 798, in __call__
    xml = self.raw(**params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 639, in _post
    return check_response_status(self.conn.getresponse())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 1097, in check_response_status
    raise ex
SolrException: HTTP code=400, reason=Bad Request
[10/Nov/2013 12:59:46] WARNING :: Not Found: /favicon.ico
[10/Nov/2013 13:02:45] ERROR :: Internal Server Error: /public/eloan/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/eloan/views.py", line 165, in eloan
    results = doSearch(solr_server, solr_core, solr_context)
  File "/Users/rjaffe/PycharmProjects/ucjeps_project/publicsearch/utils.py", line 389, in doSearch
    facet_mincount=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 703, in query
    return self.select(*args, **params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 798, in __call__
    xml = self.raw(**params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 823, in raw
    rsp = conn._post(self.selector, request, conn.form_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 639, in _post
    return check_response_status(self.conn.getresponse())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solr/core.py", line 1097, in check_response_status
    raise ex
SolrException: HTTP code=400, reason=Bad Request
